package dev.a11yagent.core.vpat;

import static dev.a11yagent.core.report.Html.esc;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.SerializationFeature;
import com.fasterxml.jackson.databind.node.ArrayNode;
import com.fasterxml.jackson.databind.node.ObjectNode;
import dev.a11yagent.core.report.Html;
import dev.a11yagent.core.wcag.Level;
import dev.a11yagent.core.wcag.WcagVersion;
import java.io.IOException;
import java.io.UncheckedIOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;
import java.util.Map;

/** A generated ACR (VPAT 2.5 WCAG edition layout) renderable as HTML, Markdown or JSON. */
public record VpatDocument(VpatOptions options, WcagVersion version, Level level, List<VpatEntry> entries,
                           List<String> pagesEvaluated, int reportsMerged) {

    private static final ObjectMapper JSON = new ObjectMapper().enable(SerializationFeature.INDENT_OUTPUT);

    public List<VpatEntry> entriesFor(Level l) {
        return entries.stream().filter(e -> e.level() == l).toList();
    }

    public Map<Conformance, Long> summary() {
        Map<Conformance, Long> m = new java.util.EnumMap<>(Conformance.class);
        for (Conformance c : Conformance.values()) {
            m.put(c, entries.stream().filter(e -> e.conformance() == c).count());
        }
        return m;
    }

    public void write(Path htmlFile, Path markdownFile, Path jsonFile) {
        try {
            if (htmlFile != null) {
                Files.createDirectories(htmlFile.toAbsolutePath().getParent());
                Files.writeString(htmlFile, toHtml());
            }
            if (markdownFile != null) {
                Files.createDirectories(markdownFile.toAbsolutePath().getParent());
                Files.writeString(markdownFile, toMarkdown());
            }
            if (jsonFile != null) {
                Files.createDirectories(jsonFile.toAbsolutePath().getParent());
                Files.writeString(jsonFile, toJson());
            }
        } catch (IOException e) {
            throw new UncheckedIOException(e);
        }
    }

    /* --------------------------------------------------------------- HTML */

    public String toHtml() {
        StringBuilder sb = new StringBuilder(32 * 1024);
        sb.append("<!doctype html><html lang=\"en\"><head><meta charset=\"utf-8\"><meta name=\"viewport\" content=\"width=device-width, initial-scale=1\"><title>")
          .append(esc(options.productName())).append(" Accessibility Conformance Report</title><style>").append(Html.CSS).append("</style></head><body><main>");
        sb.append("<h1>").append(esc(options.productName())).append(" Accessibility Conformance Report</h1>");
        sb.append("<p><strong>WCAG Edition</strong> · VPAT<sup>®</sup> Version 2.5 layout · WCAG ").append(version.label()).append(" (evaluated up to level ").append(level).append(")</p>");
        sb.append("<p class=\"muted\">Draft generated by a11y-agent from ").append(reportsMerged).append(" automated audit report(s). Conformance terms for criteria marked <em>Not Evaluated</em> or based on AI judgements must be confirmed by a human auditor before publication.</p>");

        sb.append("<h2>Report information</h2><table><tbody>");
        row(sb, "Name of Product/Version", options.productName());
        row(sb, "Report Date", String.valueOf(options.date()));
        row(sb, "Product Description", options.productDescription());
        row(sb, "Vendor", options.vendor());
        row(sb, "Contact Information", options.contact());
        row(sb, "Evaluator", options.evaluator());
        row(sb, "Notes", options.notes());
        row(sb, "Evaluation Methods Used", options.evaluationMethods());
        row(sb, "Pages evaluated", String.join(", ", pagesEvaluated));
        sb.append("</tbody></table>");

        sb.append("<h2>Applicable standards/guidelines</h2><table><thead><tr><th scope=\"col\">Standard/Guideline</th><th scope=\"col\">Included in report</th></tr></thead><tbody>");
        sb.append("<tr><td>Web Content Accessibility Guidelines ").append(version.label()).append("</td><td>Level A (Yes)<br>Level AA (").append(level.ordinal() >= 1 ? "Yes" : "No").append(")<br>Level AAA (").append(level == Level.AAA ? "Yes" : "No").append(")</td></tr></tbody></table>");

        sb.append("<h2>Terms</h2><dl><dt>Supports</dt><dd>The functionality of the product has at least one method that meets the criterion without known defects or meets with equivalent facilitation.</dd>")
          .append("<dt>Partially Supports</dt><dd>Some functionality of the product does not meet the criterion.</dd>")
          .append("<dt>Does Not Support</dt><dd>The majority of product functionality does not meet the criterion.</dd>")
          .append("<dt>Not Applicable</dt><dd>The criterion is not relevant to the product.</dd>")
          .append("<dt>Not Evaluated</dt><dd>The product has not been evaluated against the criterion. Used here for criteria without automated coverage or with unconfirmed review items.</dd></dl>");

        sb.append("<h2>Summary</h2><div class=\"grid\">");
        summary().forEach((c, n) -> sb.append("<div class=\"card ").append(c.cssClass()).append("\"><strong>").append(n).append("</strong>").append(c.label()).append("</div>"));
        sb.append("</div>");

        sb.append("<h2>WCAG ").append(version.label()).append(" Report</h2>");
        for (Level l : Level.values()) {
            if (!l.includedIn(level)) {
                continue;
            }
            List<VpatEntry> es = entriesFor(l);
            if (es.isEmpty()) {
                continue;
            }
            sb.append("<table><caption>Table ").append(l.ordinal() + 1).append(": Success Criteria, Level ").append(l).append("</caption>");
            sb.append("<thead><tr><th scope=\"col\">Criteria</th><th scope=\"col\">Conformance Level</th><th scope=\"col\">Remarks and Explanations</th></tr></thead><tbody>");
            for (VpatEntry e : es) {
                sb.append("<tr><th scope=\"row\">").append(esc(e.criterion().id())).append(" ").append(esc(e.criterion().name())).append(" (Level ").append(e.level()).append(")</th>")
                  .append("<td class=\"").append(e.conformance().cssClass()).append("\">").append(e.conformance().label()).append("</td>")
                  .append("<td>").append(esc(e.remarks())).append("</td></tr>");
            }
            sb.append("</tbody></table>");
        }
        sb.append("<footer class=\"muted\"><p>“Voluntary Product Accessibility Template” and “VPAT” are registered service marks of the Information Technology Industry Council (ITI).</p></footer>");
        sb.append("</main></body></html>");
        return sb.toString();
    }

    private static void row(StringBuilder sb, String k, String v) {
        sb.append("<tr><th scope=\"row\">").append(esc(k)).append("</th><td>").append(esc(v == null ? "" : v)).append("</td></tr>");
    }

    /* ----------------------------------------------------------- Markdown */

    public String toMarkdown() {
        StringBuilder sb = new StringBuilder(16 * 1024);
        sb.append("# ").append(options.productName()).append(" Accessibility Conformance Report\n\n");
        sb.append("**WCAG Edition** · VPAT® Version 2.5 layout · WCAG ").append(version.label()).append(" (evaluated up to level ").append(level).append(")\n\n");
        sb.append("> Draft generated by a11y-agent from ").append(reportsMerged).append(" automated audit report(s). Confirm *Not Evaluated* rows and AI-based judgements manually before publication.\n\n");
        sb.append("## Report information\n\n| Field | Value |\n|---|---|\n");
        md(sb, "Name of Product/Version", options.productName());
        md(sb, "Report Date", String.valueOf(options.date()));
        md(sb, "Product Description", options.productDescription());
        md(sb, "Vendor", options.vendor());
        md(sb, "Contact Information", options.contact());
        md(sb, "Evaluator", options.evaluator());
        md(sb, "Notes", options.notes());
        md(sb, "Evaluation Methods Used", options.evaluationMethods());
        md(sb, "Pages evaluated", String.join(", ", pagesEvaluated));
        sb.append("\n## Summary\n\n| Conformance | Criteria |\n|---|---|\n");
        summary().forEach((c, n) -> sb.append("| ").append(c.label()).append(" | ").append(n).append(" |\n"));
        for (Level l : Level.values()) {
            if (!l.includedIn(level)) {
                continue;
            }
            List<VpatEntry> es = entriesFor(l);
            if (es.isEmpty()) {
                continue;
            }
            sb.append("\n## Table ").append(l.ordinal() + 1).append(": Success Criteria, Level ").append(l).append("\n\n| Criteria | Conformance Level | Remarks and Explanations |\n|---|---|---|\n");
            for (VpatEntry e : es) {
                sb.append("| ").append(e.criterion().id()).append(" ").append(e.criterion().name()).append(" (Level ").append(e.level()).append(") | ")
                  .append(e.conformance().label()).append(" | ").append(cell(e.remarks())).append(" |\n");
            }
        }
        return sb.toString();
    }

    private static void md(StringBuilder sb, String k, String v) {
        sb.append("| ").append(k).append(" | ").append(cell(v)).append(" |\n");
    }

    private static String cell(String v) {
        return v == null ? "" : v.replace("|", "\\|").replace("\n", " ");
    }

    /* --------------------------------------------------------------- JSON */

    public String toJson() {
        ObjectNode root = JSON.createObjectNode();
        root.put("template", "VPAT 2.5 WCAG");
        root.put("wcagVersion", version.label());
        root.put("level", level.name());
        root.put("reportsMerged", reportsMerged);
        ObjectNode info = root.putObject("report");
        info.put("productName", options.productName());
        info.put("productDescription", options.productDescription());
        info.put("vendor", options.vendor());
        info.put("contact", options.contact());
        info.put("evaluator", options.evaluator());
        info.put("notes", options.notes());
        info.put("evaluationMethods", options.evaluationMethods());
        info.put("date", String.valueOf(options.date()));
        ArrayNode pages = root.putArray("pagesEvaluated");
        pagesEvaluated.forEach(pages::add);
        ObjectNode sum = root.putObject("summary");
        summary().forEach((c, n) -> sum.put(c.name(), n));
        ArrayNode rows = root.putArray("criteria");
        for (VpatEntry e : entries) {
            ObjectNode n = rows.addObject();
            n.put("id", e.criterion().id());
            n.put("name", e.criterion().name());
            n.put("level", e.level().name());
            n.put("conformance", e.conformance().label());
            n.put("remarks", e.remarks());
            n.put("failed", e.failed());
            n.put("review", e.review());
            n.put("passed", e.passed());
            n.put("automatedCoverage", e.automated());
        }
        return root.toPrettyString();
    }
}
